// An easy/recovery day is training precisely because it does NOT feel like
// a workout -- the model has no other signal that a "day" and a "workout"
// are different things, so without an explicit instruction it defaults to
// generic exertion language ("this workout... steady burn... moderate
// fatigue") that's simply wrong for these types.
function toneGuidance(workoutType: string | null): string {
  switch (workoutType) {
    case "easy":
    case "recovery":
      return "This is an easy/recovery day, not a workout -- do not call it \"a workout\" or describe any exertion, burn, or fatigue. Describe it as relaxed, conversational-effort running whose whole purpose is building aerobic base and letting the body recover. Athletes should expect to feel loose and fresh afterward, not tired.";
    case "long":
      return "This is a long run -- sustained, steady aerobic effort. Keep the tone measured, not intense; it's about endurance and time on feet, not a hard push.";
    case "tempo":
    case "vo2":
      return "This is a quality/intensity session -- real effort and some discomfort are an honest, expected part of it.";
    case "race":
      return "This is a race -- frame it around executing their race plan and trusting their training, not generic effort description.";
    default:
      return "Match the tone and intensity to what the coach's own description implies -- don't invent a difficulty level.";
  }
}

// A small, focused prompt for a coach-authored group session -- distinct
// from buildSystemPrompt (prompts.ts), which expects a structured
// WorkoutContext/prescription this doesn't have. The input here is already
// the coach's own specific free text, not a category to retrieve reference
// content for, so no retrieval step either.
export function buildGroupWorkoutExplanationPrompt(input: {
  description: string;
  workoutType: string | null;
  phaseDisplayName: string | null;
  phasePrimaryGoal: string | null;
}): string {
  const phaseContext =
    input.phaseDisplayName || input.phasePrimaryGoal
      ? `Training phase: ${input.phaseDisplayName ?? "unspecified"}.${
          input.phasePrimaryGoal ? ` This phase's goal: ${input.phasePrimaryGoal}.` : ""
        }`
      : "No season phase context is available for this entry.";

  return `You are helping a high school cross country coach explain one of their own written training sessions to their athletes.

The coach wrote this session themselves -- it is not generated by you, and you must not invent numbers, distances, or paces that aren't already in it.

Session description (the coach's own words): "${input.description}"
${input.workoutType ? `Classified as: ${input.workoutType}.` : ""}
${phaseContext}
${toneGuidance(input.workoutType)}

Write 2-3 short, plain-language sentences explaining what this specific session is for and what an athlete should expect to feel -- grounded in the training phase context and tone guidance above. Do not restate the description verbatim. Do not mention specific paces or distances unless the coach's own description already includes them. Do not use headers, bullet points, or labels -- just the sentences themselves, ready to show an athlete directly.`;
}
